name: medicinelocator1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.1.0
  #firebase_messaging: ^15.0.2
  #google_mlkit_text_recognition: ^0.3.0
  #flutter_local_notifications: ^17.1.2
  #google_maps_flutter: ^2.6.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  #firebase_ml_vision: ^0.12.0+3
  provider: ^6.1.2
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  google_ml_kit: ^0.11.0
  firebase_ml_model_downloader: ^0.3.0+2
 # location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
